//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EFNET
{
    using System;
    using System.Collections.Generic;
    
    public partial class report
    {
        public int reportId { get; set; }
        public string reportName { get; set; }
        public int seriesId { get; set; }
        public Nullable<System.DateTime> TimeStamp { get; set; }
    
        public virtual series series { get; set; }
    }
}
