//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EFNET
{
    using System;
    using System.Collections.Generic;
    
    public partial class study
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public study()
        {
            this.series = new HashSet<series>();
        }
    
        public int studyId { get; set; }
        public string studyName { get; set; }
        public int patientId { get; set; }
        public Nullable<System.DateTime> TimeStamp { get; set; }
    
        public virtual patient patient { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<series> series { get; set; }
    }
}
