//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EFNET
{
    using System;
    using System.Collections.Generic;
    
    public partial class user
    {
        public int userId { get; set; }
        public string userName { get; set; }
        public string password { get; set; }
        public string firstName { get; set; }
        public string lastName { get; set; }
        public string gender { get; set; }
        public System.DateTime DOB { get; set; }
        public string email { get; set; }
        public int roleId { get; set; }
    
        public virtual role role { get; set; }
    }
}
